export class ContractChangeHistory{
    id:number;
    id_contract:number;
    date:Date;
    id_request:number;
    id_customer:number;
    name_contract_owner:String;
    payment_period:String;
    insurance_type:String;
    id_main_interest:number;
    id_illustration:number;
    start_time:Date;
    end_time:Date;
    status:String;
    approval_status:String;
    contract_total_value:number;
    date_next_payment:Date;   
    id_employee:number;
}